---
roles:
  - name: opentelekomcloud.vpc
  - name: opentelekomcloud.keypair
  - name: opentelekomcloud.bastion
  - name: opentelekomcloud.server_common
  - name: opentelekomcloud.security_group
collections:
  - name: opentelekomcloud.cloud
    version: 0.7.0
  - name: openstack.cloud
    version: 1.2.1
