---
# tasks file for roles/volume_create_delete

- name: Set Fact if volume_type is not defined
  set_fact:
    volume_type: false
  when: volume_type is not defined

- block:
  - name: "Create SSD Volume in {{ availability_zone }}"
    when: volume_type == "SSD"
    openstack.cloud.volume:
      state: present
      availability_zone: "{{ availability_zone | default(omit) }}"
      size: 10
      volume_type: "{{ volume_type }}"
      display_name: "{{ volume_name }}"
    tags:
      - "metric=create_volume"
      - "metric=create_volume_SSD"
    register: volume

  - name: "Create SAS Volume in {{ availability_zone }}"
    when: volume_type == "SAS"
    openstack.cloud.volume:
      state: present
      availability_zone: "{{ availability_zone | default(omit) }}"
      size: 10
      volume_type: "{{ volume_type }}"
      display_name: "{{ volume_name }}"
    tags:
      - "metric=create_volume"
      - "metric=create_volume_SAS"
    register: volume

  - name: "Create Volume in {{ availability_zone }}"
    when: not volume_type
    openstack.cloud.volume:
      state: present
      availability_zone: "{{ availability_zone | default(omit) }}"
      size: 10
      display_name: "{{ volume_name }}"
    tags:
      - "metric=create_volume"
  
  always:
    - name: "Delete Volume"
      openstack.cloud.volume:
        state: absent
        display_name: "{{ volume_name }}"
      tags:
        - "metric=delete_volume"
        - "metric=delete_volume_{{ availability_zone }}"
