---
- name: Scenario 18 - CCE cluster with worker nodes 
  hosts: localhost
  vars:
    prefix: scenario18a-
    test_cce_flavor: cce.s1.small
    test_cce_container_network_mode: overlay_l2
    test_node_flavor: s3.large.2
    test_node_os: 'EulerOS 2.9'
    test_volume_type: SSD
    test_volume_size: 100

  tasks:
    - set_fact:
        prefix: "{{ (prefix + ( lookup('env', 'TASK_EXECUTOR_JOB_ID') | default(99999999 | random | to_uuid | hash('md5'), true) ) ) }}"

    - set_fact:
        test_router_name: "{{ (prefix + '-test_router_apimon') }}"
        test_subnet_name: "{{ (prefix + '-test_subnet_apimon') }}"
        test_network_name: "{{ (prefix + '-test_network_apimon') }}"
        test_cluster_name: "{{ ('z-' + prefix + '-cluster') }}"
        test_keypair_name: "{{ ( prefix + '-cce-kp' ) }}"
        test_node_name: "{{ ( prefix + '-node' ) }}"
        test_node_pool_name: "{{ ( prefix + '-pool' ) }}"

    - block:

      - name: Create VPC (Router + Net + Subnet)
        include_role:
          name: opentelekomcloud.vpc
        vars:
          router_name: "{{ test_router_name }}"
          network_name: "{{ test_network_name }}"
          subnet_name: "{{ test_subnet_name }}"
          state: present

      - name: Create Keypair
        include_role:
          name: opentelekomcloud.keypair
        vars:
          keypair_name: "{{ test_keypair_name }}"
          state: "present"

      - name: Get Availability zones
        opentelekomcloud.cloud.availability_zone_info:
        register: azs

      - name: Create CCE Cluster
        opentelekomcloud.cloud.cce_cluster:
          state: present
          name: "{{ test_cluster_name }}"
          flavor: "{{ test_cce_flavor }}"
          description: "APImon test"
          router: "{{ test_router_name }}"
          network: "{{ test_network_name }}"
          container_network_mode: "{{ test_cce_container_network_mode }}"
          wait: true
        register: cluster
        tags:
          - 'service=cce'
          - 'metric=create_cce_cluster'

      - name: Create NodePool Node
        opentelekomcloud.cloud.cce_node_pool:
          availability_zone: "{{ az }}"
          cluster: "{{ test_cluster_name }}"
          initial_node_count: 1
          data_volumes:
            - volumetype: "{{ test_volume_type }}"
              size: "{{ test_volume_size }}"
          flavor: "{{ test_node_flavor }}"
          ssh_key: "{{ test_keypair_name }}"
          name: "{{ test_node_pool_name }}"
          network: "{{ test_network_name }}"
          os: "{{ test_node_os }}"
          root_volume_size: "{{ test_volume_size }}"
          root_volume_type: "{{ test_volume_type }}"
          wait: false
          timeout: 300
          state: present
        register: pool
        vars:
          az: "{{ azs['availability_zones'][1]['name'] }}"

      - name: Create Worker Node
        opentelekomcloud.cloud.cce_cluster_node:
          availability_zone: "{{ az }}"
          cluster: "{{ test_cluster_name }}"
          count: 1
          data_volumes:
            - volumetype: "{{ test_volume_type }}"
              size: "{{ test_volume_size }}"
          flavor: "{{ test_node_flavor }}"
          ssh_key: "{{ test_keypair_name }}"
          name: "{{ test_node_name }}"
          network: "{{ test_network_name }}"
          os: "{{ test_node_os }}"
          root_volume_size: "{{ test_volume_size }}"
          root_volume_type: "{{ test_volume_type }}"
          wait: true
          timeout: 300
          state: present
        vars:
          az: "{{ azs['availability_zones'][0]['name'] }}"

      - name: Query CCE Cluster
        opentelekomcloud.cloud.cce_cluster_info:
          name: "{{ test_cluster_name }}"
        register: cluster_info

      - name: Query NodePool Node
        opentelekomcloud.cloud.cce_node_pool_info:
          cce_cluster: "{{ test_cluster_name }}"
        register: pool
        # purpose of wait:false for nodepool is to have simoultaneous creation of 2 nodes
        until: pool.cce_node_pools[0].status.status == ""
        retries: 30
        delay: 5

      - name: Query Worker  Node 
        opentelekomcloud.cloud.cce_cluster_node_info:
          cce_cluster: "{{ test_cluster_name }}"
          name: "{{ test_node_name }}"
        register: node

      - name: Delete CCE Cluster
        opentelekomcloud.cloud.cce_cluster:
          name: "{{ test_cluster_name }}"
          state: "absent"
          wait: true
        tags:
          - 'service_cce'
          - 'metric=delete_cce_cluster'

      always:
        - block:
          - name: Delete Keypair
            include_role:
              name: opentelekomcloud.keypair
            vars:
              keypair_name: "{{ test_keypair_name }}"
              state: "absent"

          - name: Delete VPC
            include_role:
              name: opentelekomcloud.vpc
            vars:
              router_name: "{{ test_router_name }}"
              network_name: "{{ test_network_name }}"
              subnet_name: "{{ test_subnet_name }}"
              state: absent
          ignore_errors: true
