---

- name: RDS lifecycle - basic RDS functionality
  hosts: localhost
  vars:
    prefix: rds-
    test_router_name: "apimon-test-rds-router"
    test_network_name: "apimon-test-rds-network"
    test_subnet_name: "apimon-test-rds-subnet"
    test_security_group_name: "apimon-test-rds-sg"

  tasks:
    # Set random ID of the run
    - name: Set random ID of the run
      set_fact:
        rid: "{{ lookup('env', 'TASK_EXECUTOR_JOB_ID') | default(999999 | random, true) }}"

    # Combine it with the prefix and ensure it's truncated
    - name: Combine prefix with RID
      set_fact:
        prefix: "{{ ('rds-' + rid | string)[:10] }}"

    # Set all neccessary names combine with prefix
    - set_fact:
        test_rds_name: "{{  prefix  }}"
        password: "{{ ('Test8*' + prefix)[:20] }}"  # Ensure the password is within 20 characters

    # Query all available Availability zones
    - name: Get Availability zones
      opentelekomcloud.cloud.availability_zone_info:
      register: azs

    # Random selection of AZ
    - name: Get a random availability zone name
      set_fact:
        random_az: "{{ azs.availability_zones | map(attribute='name') | list | random }}"

    # Random selection between MySQL and PostgreSQL db engine
    - name: Random selection of DB type
      set_fact:
        db_type: "{{ ['mysql', 'postgresql'] | random }}"

    # Query all present versions of previously selected DB engine
    - name: Get datastore info
      opentelekomcloud.cloud.rds_datastore_info:
        datastore: "{{  db_type  }}"
      register: versions

    # Query all flavoers for specific DB engine
    - name: Get info about choosen type of DB
      opentelekomcloud.cloud.rds_flavor_info:
        datastore: "{{ db_type }}"
        instance_mode: "single"
      register: rds_flavors

    # Run python script to get Region, Storage type and Latest version of DB engine
    - name: Run Python script to find the latest version
      script: >
        {{ playbook_dir }}/files/rds_preconditions.py
        '{{ db_type }}'
        '{{ versions.rds_datastores | to_nice_json }}'
        '{{ rds_flavors.rds_flavors | to_nice_json }}'
        '{{ random_az }}'
      args:
        executable: python3
      register: script_output

    - name: Parse JSON output from script
      set_fact:
        script_vars: "{{ script_output.stdout | from_json }}"

    - name: Set region, storage_type, and latest_version
      set_fact:
        region: "{{ script_vars.region }}"
        storage_type: "{{ script_vars.storage_type }}"
        latest_version: "{{ script_vars.latest_version }}"
        smallest_flavor: "{{ script_vars.smallest_flavor }}"

    - name: Display region and storage_type
      debug:
        msg:
          - "Prefix: {{ prefix }}"        
          - "Region: {{ region }}"
          - "AZ": "{{ random_az }}"
          - "Storage Type: {{ storage_type }}"
          - "DB Type: {{ db_type }}"          
          - "Latest vesion: {{ latest_version }}"
          - "Smallest flavor: {{ smallest_flavor }}"

   
    - block:
      # Check if the VPC (Router + Network + Subnet) exists
      - name: Check if Network exists
        openstack.cloud.networks_info:
          name: "{{ test_network_name }}"
        register: network_check

      # Create VPC and Subnet only if the network doesn't exist
      - name: Create VPC (Router + Net + Subnet) if it doesn't exist
        include_role:
          name: opentelekomcloud.vpc
        vars:
          router_name: "{{ test_router_name }}"
          network_name: "{{ test_network_name }}"
          subnet_name: "{{ test_subnet_name }}"
          state: present

      # Check if the Security Group exists
      - name: Check if Security Group exists
        openstack.cloud.security_group_info:
          name: "{{ test_security_group_name }}"
        register: sg_check

      # Create Security Group only if it doesn't exist
      - name: Create Security Group if it doesn't exist
        openstack.cloud.security_group:
          name: "{{ test_security_group_name }}"
          description: RDS test SG created by APImon

      # Create RDS instance MySQL
      - name: Create RDS instance MySQL
        when: db_type == "mysql"
        opentelekomcloud.cloud.rds_instance:
          name: "{{ test_rds_name }}"
          state: present
          availability_zone: "{{ random_az }}"
          datastore_type: "{{ db_type }}"
          datastore_version: "{{ latest_version }}"
          flavor: "{{ smallest_flavor }}"
          router: "{{ test_router_name }}"
          network: "{{ test_network_name }}"
          security_group: "{{ test_security_group_name }}"
          password: "{{ password }}"
          volume_type: "{{ storage_type }}"
          region: "{{ region }}"
          volume_size: 40
          backup_keepdays: 0
          # backup_timeframe: "02:00-03:00"
          wait: true
          timeout: 777
        register: rds_mysql
        tags:
          - 'service=rds'
          - 'metric=create_rds_mysql'

      - set_fact: 
          rds: "{{ rds_mysql }}"
        when: db_type == "mysql"

      # Create RDS instance PostgreSQL
      - name: Create RDS instance PostgreSQL
        when: db_type == "postgresql"
        opentelekomcloud.cloud.rds_instance:
          name: "{{ test_rds_name }}"
          state: present
          availability_zone: "{{ random_az }}"
          datastore_type: "{{  db_type }}"
          datastore_version: "{{ latest_version }}"
          flavor: "{{ smallest_flavor }}"
          router: "{{ test_router_name }}"
          network: "{{ test_network_name }}"
          security_group: "{{ test_security_group_name }}"
          password: "{{ password }}"
          volume_type: "{{ storage_type }}"
          region: "{{ region }}"
          volume_size: 40
          backup_keepdays: 0
          # backup_timeframe: "02:00-03:00"
          wait: true
          timeout: 777
        register: rds_pg
        tags:
          - 'service=rds'
          - 'metric=create_rds_postgresql'

      - set_fact: 
          rds: "{{ rds_pg }}"
        when: db_type == "postgresql"


      # With this info module you can get info about your instance
      - name: Let's get info about whole RDS instance
        opentelekomcloud.cloud.rds_instance_info:
          name: "{{ rds.instance.name }}"

      - name: Let's get info about datastore
        opentelekomcloud.cloud.rds_datastore_info:
          name: "{{ rds.instance.id }}"


      # Querying RDS backup info
      - name: Get RDS backup info
        opentelekomcloud.cloud.rds_backup_info:
          instance: "{{ rds.instance.id }}"
    
      always:
        - block:

          # Delete RDS instance PostgreSQL
          - name: Now Delete RDS instance PostgreSQL
            when: db_type == "postgresql"
            opentelekomcloud.cloud.rds_instance:
              name: "{{ rds.instance.id }}"
              state: absent
              wait: true
            tags:
              - 'service=rds'
              - "metric=delete_rds_postgresql"

          # Delete RDS instance MySQL
          - name: Now Delete RDS instance MySQL
            when: db_type == "mysql"
            opentelekomcloud.cloud.rds_instance:
              name: "{{ rds.instance.id }}"
              state: absent
              wait: true
            tags:
              - 'service=rds'
              - "metric=delete_rds_mysql"
     
          ignore_errors: true