---
#  Scenario to test basic SMN topic lifecycle scenario

- name: Scenario 24 - SMN Topic
  hosts: localhost
  vars:
    prefix: scenario24-
  tasks:
    - set_fact:
        prefix: "{{ (prefix + ( lookup('env', 'TASK_EXECUTOR_JOB_ID') | default(99999999 | random | to_uuid | hash('md5'), true) ) ) }}"

    - set_fact:
        test_smn_topic: "{{ (prefix + 'topic') }}"
    
   
    - block:

      - name: Create SMN Topic
        script: "create_smn_topic.py {{ test_smn_topic }}"
        args:
          executable: python3
        register: result_create_topic

      - name: Get topic_urn
        set_fact:
          topic_urn: "{{ result_create_topic.stdout.strip() }}"

      - debug:
          msg: "topic_urn: {{ topic_urn }}"

      - name: Query Topics
        script: "list_smn_topics.py"
        args:
          executable: python3
      
      - name: Query Created Topic
        script: "get_smn_topic.py {{ topic_urn }}"
        args:
          executable: python3
 
      - name: Update SMN Topic
        script: "update_smn_topic.py {{ topic_urn }} display_{{ test_smn_topic }}"
        args:
          executable: python3
 
      # Temporary commented out due to crashes with libraries on env. It will be reactivated once this is fixed
      
      # - name: Update Topic Policy
      #   script: "update_smn_topic_policy.py {{ topic_urn }}"
      #   args:
      #     executable: python3

      - name: Query Topic Policy
        script: "get_smn_topic_policy.py {{ topic_urn }}"
        args:
          executable: python3
        
      
      always:
        - block:

          - name: Delete SMN Topic
            script: "delete_smn_topic.py {{ topic_urn }}"
            args:
              executable: python3
          
          ignore_errors: true
      
      
        
     
